/**
 * Read-only source of bundled problems (fetch + validate). This is the ONLY
 * fetch point in src/problems — read.ts / solve.ts / templates.ts stay pure.
 *
 * The data under /problems/ is generated by scripts/build-problems.mjs and
 * proven by tests (chess.js replay of every solution), so runtime validation
 * here is STRUCTURAL only: a malformed file is a real error, not something
 * to silently skip.
 */
import type { Problem, ProblemManifest, ProblemSource, ProblemThemeInfo } from '../types'

const LOAD_FAILED = 'The problem set failed to load — try reloading.'

/** UCI move: from-square, to-square, optional promotion piece. */
const UCI_RE = /^[a-h][1-8][a-h][1-8][qrbnQRBN]?$/

/**
 * Solutions are 2–4 movers (CONTEXT.md, PLAN §8.2): the opponent's setup move
 * plus 3, 5, or 7 plies. Single source of truth for the allowed lengths —
 * data.test.ts imports this so the bundled data and this runtime validator
 * can never drift apart again.
 */
export const SOLUTION_MOVES_LENGTHS = [4, 6, 8]

function isNonEmptyString(v: unknown): v is string {
  return typeof v === 'string' && v.length > 0
}

function isFiniteNumber(v: unknown): v is number {
  return typeof v === 'number' && Number.isFinite(v)
}

function isValidProblem(v: unknown): v is Problem {
  if (typeof v !== 'object' || v === null) return false
  const p = v as Partial<Problem>
  return (
    isNonEmptyString(p.id) &&
    isNonEmptyString(p.fen) &&
    Array.isArray(p.moves) &&
    SOLUTION_MOVES_LENGTHS.includes(p.moves.length) &&
    p.moves.every((m) => typeof m === 'string' && UCI_RE.test(m)) &&
    isFiniteNumber(p.rating) &&
    Array.isArray(p.themes) &&
    p.themes.every((t) => typeof t === 'string')
  )
}

function isValidThemeInfo(v: unknown): v is ProblemThemeInfo {
  if (typeof v !== 'object' || v === null) return false
  const t = v as Partial<ProblemThemeInfo>
  return (
    isNonEmptyString(t.id) &&
    isNonEmptyString(t.name) &&
    typeof t.description === 'string' &&
    isNonEmptyString(t.file) &&
    isFiniteNumber(t.count)
  )
}

function isValidManifest(v: unknown): v is ProblemManifest {
  if (typeof v !== 'object' || v === null) return false
  const m = v as Partial<ProblemManifest>
  return (
    isNonEmptyString(m.source) &&
    isNonEmptyString(m.sourceDate) &&
    isNonEmptyString(m.generatedAt) &&
    isNonEmptyString(m.license) &&
    isFiniteNumber(m.ratingMin) &&
    isFiniteNumber(m.ratingMax) &&
    isFiniteNumber(m.total) &&
    Array.isArray(m.themes) &&
    m.themes.length > 0 &&
    m.themes.every(isValidThemeInfo)
  )
}

async function fetchJson(url: string): Promise<unknown> {
  let response: Response
  try {
    response = await fetch(url)
  } catch {
    throw new Error(LOAD_FAILED)
  }
  if (!response.ok) throw new Error(LOAD_FAILED)
  try {
    return await response.json()
  } catch {
    throw new Error(LOAD_FAILED)
  }
}

/**
 * Create the bundled-problem source. `baseUrl` points at the directory the
 * build pipeline writes (default: /problems, served from public/problems).
 * The parsed manifest and each theme file are cached in memory — the data is
 * immutable at runtime.
 */
export function createProblemSource(baseUrl = '/problems'): ProblemSource {
  let cachedManifest: ProblemManifest | undefined
  const themeCache = new Map<string, Problem[]>()

  const manifest = async (): Promise<ProblemManifest> => {
    if (cachedManifest) return cachedManifest
    const json = await fetchJson(`${baseUrl}/manifest.json`)
    if (!isValidManifest(json)) throw new Error(LOAD_FAILED)
    cachedManifest = json
    return json
  }

  const theme = async (themeId: string): Promise<Problem[]> => {
    const cached = themeCache.get(themeId)
    if (cached) return cached
    const info = (await manifest()).themes.find((t) => t.id === themeId)
    if (!info) {
      throw new Error(`Unknown problem theme "${themeId}" — try reloading.`)
    }
    const json = await fetchJson(`${baseUrl}/${info.file}`)
    if (!Array.isArray(json) || json.length === 0) throw new Error(LOAD_FAILED)
    for (const entry of json) {
      if (!isValidProblem(entry)) {
        // Bundled data is proven by tests; a malformed entry is a real bug.
        throw new Error(`Problem file "${info.file}" contains a malformed problem.`)
      }
    }
    const problems = json as Problem[]
    themeCache.set(themeId, problems)
    return problems
  }

  return { manifest, theme }
}
